version: '3'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: SqlApiModelo
    restart: "always"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sa@12345